name: try
on:
    push:
        branches:
            - v[0-9]+.[0-9]

jobs:
    try_workflow:
        if: startsWith(github.event.head_commit.message, '#norun') != true
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Run Trivy vulnerability scanner in repo mode
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: 'fs'
              ignore-unfixed: true
              format: 'table'
              output: 'trivy-results.txt'
              severity: 'CRITICAL,HIGH'
              exit-code: 1

          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: ${{ job.status }}
              SLACK_USERNAME: LIU SHIYU
              SLACK_TITLE: Message
              SLACK_MESSAGE: |
                *NAME:*LIUSHIYU
                *ID:*A0286059R
                *EMAIL:*e1221871@u.nus.edu
                *GITHUB*github:https://github.com/${{ github.repository }}/tree/v1.0
                *DOCKER:*https://hub.docker.com/repository/docker/liushiyu625/httpd/general
              SLACK_WEBHOOK: ${{ secrets.TEST }}

          - name: Slack Failed Notification
            if: failure()
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: '#ff0000'
              SLACK_USERNAME: LIU SHIYU
              SLACK_TITLE: Scan failed
              SLACK_MESSAGE: |
                Failed trivy scan,see uploaded report

          - name: Install Cosign
            uses: sigstore/cosign-installer@v3.1.1
            
          - name: Check install!
            run: cosign version

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2.1.0
             
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2.5.0
             
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push
            uses: docker/build-push-action@v5
            id: sy
            with:
              context: .
              push: true
              tags: |
                liushiyu625/httpd:latestz
              
          - name: Sign image with a key
            run: |
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
            env:
              TAGS: liushiyu625/httpd:latestz
              COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
              COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
              
          - uses: MeilCli/slack-upload-file@v3
            if: failure()
            with:
              slack_token: ${{ secrets.SLACK_TOKEN }}
              channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
              file_path: 'trivy-results.txt'
              initial_comment: 'post by sy'
              content: 'file content'
              