name: try
on:
    push:
        branches:
            - v[0-9]+.[0-9]

jobs:
    try_workflow:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                trivy-config: try.yaml



            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
                env: 
                SLACK_CHANNEL: cicd-workshop
                SLACK_COLOR: ${{ job.status }} 
                SLACK_TITLE: STUDENT-ID 123456
                SLACK_TITLE: email 12356
                SLACK_USERNAME: LIU SHIYU

                SLACK_WEBHOOK: ${{ secrets.TRY}}
   