name: try
on:
    push:
        branches:
            - v[0-9]+.[0-9]

jobs:
    try_workflow:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            
            - name: Run Trivy vulnerability scanner in fs mode
              uses: anandg112/trivy-action@feat/add-skip-dirs-option
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif '
                output: 'trivy-results-fs.sarif'
                severity: 'CRITICAL'
                skip-dirs: "ignored-dir"
                 

            - uses: MeilCli/slack-upload-file@v3
              with:
               slack_token: ${{ secrets.SLACK_TOKEN }}
               channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
               content: 'file content'
               file_type: 'text'
               file_name: 'text.txt'
               title: 'title of file'
               initial_comment: 'post by slack-upload-file'
             

               
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
             
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
             
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                content: 'file content'
                file_type: 'text'
                file_name: 'text.txt'
                title: 'title of file'
                initial_comment: 'post by slack-upload-file'


           
           
        
   