name: try
on:
    push:
        branches:
            - v[0-9]+.[0-9]

jobs:
    try_workflow:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                trivy-config: try.yaml
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL,HIGH'



           
           
        
   