name: try
on:
    push:
        branches:
            - v[0-9]+.[0-9]

jobs:
    try_workflow:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                trivy-config: try.yaml



            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env: 
                SLACK_CHANNEL: cicd-workshop
                SLACK_COLOR: ${{ job.status }}
                SLACK_USERNAME: LIU SHIYU
                SLACK_WEBHOOK: ${{ secrets.TRY}}
              run:
                messages=(
                " 1 Title: Message 1 Content"
                " 2 Title: Message 2 Content"
                " 3 Title: Message 3 Content")
        
   